[package]
name        = "osmo-proto"
authors     = [""]
description = "Osmosis proto helpers"
keywords    = ["osmosis", "protobuf", "cosmwasm"]
version     = { workspace = true }
edition     = { workspace = true }
homepage    = { workspace = true }
repository  = { workspace = true }
license     = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost           = { workspace = true }
prost-types     = { workspace = true }
cosmwasm-std    = { workspace = true, features = ["stargate"] }
